- examples/moments/backend/src/methods/create_moment.ts
- packages/drops/package.json
- packages/moments/package.json
- packages/moments/src/client/MomentsClient.spec.ts
- packages/moments/src/client/MomentsClient.ts
- packages/moments/src/client/dtos/create/CreateInput.ts
- packages/poaps/package.json
- packages/providers/package.json
- packages/providers/src/core/PoapMomentsApi/PoapMomentsApi.ts
- packages/utils/package.json
- yarn.lock
In Moments, change the file binary from `Buffer` to `UInt8Array`, so, now, it's compatible with both node and browsers.
> Moments: Change File Binary Type

- examples/drops/backend/.env.template
- examples/drops/backend/src/index.ts
- packages/drops/package.json
- packages/drops/src/DropsClient.ts
- packages/drops/src/domain/Drop.ts
- packages/drops/src/queries/PaginatedDrop.ts
- packages/drops/src/types/dropImage.ts
* Adds `drop_image` object to the drop query
* Adds `originalImageUrl` property to the drop response
Contributes to [CEX-910](https://poap-devs.atlassian.net/browse/IEX-910)
> feat(IEX-910): Add original image URL property to drop

- packages/drops/package.json
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/providers/src/core/PoapCompass/PoapCompass.ts
- packages/providers/src/ports/CompassProvider/CompassProvider.ts
- packages/providers/src/ports/CompassProvider/errors/CompassRequestError.ts
- packages/providers/src/ports/CompassProvider/types/CompassError.ts
- packages/providers/src/ports/CompassProvider/types/CompassErrors.ts
- packages/providers/test/PoapCompass.spec.ts
- packages/utils/package.json
- yarn.lock
The compass error management was not good to understand what was happening under. It had some problems like doing a `response.json` when the status code is not 200, double-throw without needed in request/fetchGraphQL and the catch was for everything instead of more fine-grained problems. Now there is a custom error that will return GraphQL errors. Also, changed the use of `any` for `unknown` and remove the `ts-ignore`.
> Improve Compass types and errors

- docs/pages/packages/drops.mdx
- docs/pages/packages/moments.mdx
- docs/pages/packages/providers.mdx
- examples/drops/backend/package.json
- examples/poaps/backend/package.json
- packages/drops/README.md
- packages/moments/README.md
- packages/providers/README.md
- yarn.lock
Update documentation to not include anymore `form-data`
> [ Documentation ] Remove form-data from all documentation

- packages/providers/src/core/PoapCompass/PoapCompass.ts
- packages/providers/src/ports/CompassProvider/errors/CompassMissingDataError.ts
- packages/providers/src/ports/CompassProvider/errors/index.ts
- packages/providers/test/PoapCompass.spec.ts
This we need to consider if Compass will ever have a request that will not return any data --it has not been the case for the moment.
We can also move the validation to another method call `query` to be explicitly know that the request will return some data.
> Validate on compass that returns data

- packages/providers/src/core/PoapCompass/PoapCompass.ts
- packages/providers/src/ports/CompassProvider/CompassProvider.ts
Add an `AbortSignal` to the compass provider request so it can be aborted.
> Allow compass requests to be aborted

- docs/README.md
The docs readme was saying to use npm, but there is no `package-lock.json`, instead there is a `yarn.lock`, so yarn must be used instead.
> Use yarn in docs readme

- .github/workflows/npm_publish.yml
- .github/workflows/npm_publish_tag.yml
- .github/workflows/run-tests.yml
- packages/drops/package.json
- packages/moments/package.json
- packages/poaps/package.json
- packages/poaps/src/PoapsClient.ts
- packages/poaps/test/PoapsClient.spec.ts
- packages/poaps/test/index.spec.ts
- packages/providers/package.json
- packages/utils/package.json
- packages/utils/src/queries/filter.ts
- yarn.lock
This fix that a fetch with `collectorAddress` and `filter*Address` returned incorrectly all except of the ones from the collector.
> Fix fetch POAPs with collector and without null address filter

- packages/utils/src/queries/order.ts
- packages/utils/src/types/order.ts
Make `OrderBy` recursive.
Related to #113
> Make OrderBy type recursive

- docs/pages/packages/moments.mdx
- examples/moments/backend/src/index.ts
- examples/moments/backend/src/methods/patch_moment.ts
- packages/drops/package.json
- packages/moments/package.json
- packages/moments/src/client/MomentsClient.spec.ts
- packages/moments/src/client/MomentsClient.ts
- packages/moments/src/client/dtos/patch/PatchInput.ts
- packages/moments/src/domain/Moment.ts
- packages/moments/src/index.ts
- packages/moments/src/queries/PaginatedMoments.ts
- packages/poaps/package.json
- packages/providers/package.json
- packages/providers/src/core/PoapMomentsApi/PoapMomentsApi.ts
- packages/providers/src/ports/MomentsApiProvider/MomentsApiProvider.ts
- packages/providers/src/ports/MomentsApiProvider/types/CreateMomentResponse.ts
- packages/providers/src/ports/MomentsApiProvider/types/PatchMomentInput.ts
- packages/providers/test/PoapMomentsApi.spec.ts
- packages/utils/package.json
- yarn.lock
Adding the cid field to the get Moments calls, that reflects the moment stored in Registry as well as the new patch Moment method that currently only supports cid and that has auth0 protection.
The cid of the moment in Registry under the format: `<Version>-<Signer>-<Signature>.<Type>` allows you to fetch and verify the content of the moment in Registry.
> [Moments] - Add cid field and patch request

- README.md
Fixed typos in the documentation:
- Added missing articles and prepositions.
- Corrected grammatical errors.
- Improved sentence structure for better readability.
- [ X ] Documentation update (if none of the other choices apply)
- [X ] I have read the [CONTRIBUTING](https://github.com/poap-xyz/poap.js/blob/main/documentation/CONTRIBUTING.md) document.
- [X ] I have added tests to cover my changes.
- [ X] All new and existing tests passed.
- [X ] I have updated the documentation accordingly.
> docs: Improve phrasing and fix typos in README.md

- packages/drops/package.json
- packages/drops/src/DropsClient.ts
- packages/drops/src/types/CreateDropsInput.ts
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- packages/utils/src/format/index.ts
- packages/utils/src/format/toPOAPDate.ts
- yarn.lock
Allows drops to be created passing `Date` objects to `startDate`, `endDate` and `expiryDate` instead of formatted strings.
Fixes #65
> Drops created with Date

- packages/drops/package.json
- packages/drops/src/domain/Drop.ts
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- yarn.lock
Fix when email claims stats is null.
> Default email reservation count to zero

- packages/drops/package.json
- packages/drops/src/domain/Drop.ts
- packages/drops/src/queries/PaginatedDrop.ts
- packages/drops/src/queries/SearchDrops.ts
- packages/drops/src/types/DropResponse.ts
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- yarn.lock
The email reservation count for a drop includes reservations that have been minted already, and therefore skews the total collectors count in place where you want to do: `mint count + reservation count = total collectors count`.
A possibility is to keep both counts (minted and reserved), and choose which is preferred on each client. Worth discussing if we think that's needed.
> feat: Exclude minted drop email reservations in total count

- docs/pages/packages/drops/CreateDrop.mdx
- docs/pages/packages/drops/FetchDrops.mdx
- docs/pages/packages/poaps/EmailReservation.mdx
- docs/pages/packages/poaps/Mint.mdx
Hello
I found and fixed several spelling issues.
Br, Elias.
> Docs fix spelling issues

- docs/pages/changelog.mdx
- packages/drops/package.json
- packages/providers/package.json
- packages/providers/src/core/PoapCompass/PoapCompass.ts
- packages/providers/src/ports/CompassProvider/CompassProvider.ts
- yarn.lock
* Allows a client to disable cache in next.js requests for example
* Signal can still be given through these options
Feedback welcome.
> feat: Allow passing in fetch options to compass requests

- packages/drops/package.json
- packages/drops/src/domain/Drop.ts
- packages/drops/src/index.ts
* Adds a deserialization method to the `Drop` class.
* Also export the `SerializableDrop` interface for strict typescript check purpose in clients.
Closes #74
> feat: Add method to transform a Serializable Drop into a Drop

- packages/poaps/package.json
- yarn.lock
The poap package was still on a previous version, making the Compass Provider incompatible with version 0.7.0 of `@poap-xyz/providers`.
> build: Upgrade providers package version on poaps package

- packages/drops/package.json
- packages/moments/package.json
- packages/moments/src/client/MomentsClient.spec.ts
- packages/moments/src/client/dtos/create/CreateAndUploadInput.ts
- packages/moments/src/client/dtos/create/CreateInput.ts
- packages/poaps/package.json
- packages/providers/package.json
- packages/providers/src/ports/MomentsApiProvider/types/CreateMomentInput.ts
- packages/providers/test/PoapMomentsApi.spec.ts
- packages/utils/package.json
- yarn.lock
To create a Moment without any drop links, it was mandatory to pass in an empty array. This is not a requirement in the API, so this PR removes the requirement from the SDK as well.
> refactor: Make the drop IDs property optional when creating a Moment

- packages/drops/package.json
- packages/drops/src/domain/Drop.ts
- packages/drops/src/domain/DropImage.ts
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- yarn.lock
This fixes when a Drop has no `drop_image` returned.
> Fix Drop from Compass without Image

- docs/pages/packages/poaps/Mint.mdx
- docs/pages/packages/utils.mdx
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "can simplified" to "can be simplified".
Corrected "can done" to "can be done".
Corrected "auxiliar functions" to "auxiliary functions".
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- packages/drops/README.md
This pull request fixes a typo in the example code for setting up API keys. Specifically, the following line contains an incorrect usage:
```javascript
new PoapCompass('you_api_key'),
```
**Error:** `you_api_key`  
**Correction:** It should be `your_api_key`.
Corrected code:
```javascript
new PoapCompass('your_api_key'),
```
**Reasoning:**
The corrected version uses the grammatically appropriate form **"your"**, which is the correct possessive form. This aligns with the rest of the document where **"your_api_key"** is used consistently. It follows standard conventions for API key examples and avoids the confusion caused by the incorrect usage of "you" as a possessive adjective.
This change ensures consistency and clarity in the documentation.
> Fix Typo in Update README.md

- README.md
- docs/README.md
- packages/drops/README.md
- packages/frames/README.md
- packages/moments/README.md
- packages/poaps/README.md
- packages/providers/README.md
- packages/utils/README.md
- Wrap text lines to 120 chars.
- Add links to CONTRIBUTING file.
- Put package names in code quotes.
- Removes example sections.
- Put links to SDK documentation.
Closes # (issue)
> Small READMEs fixes

- packages/moments/README.md
- packages/providers/README.md
- packages/utils/README.md
- Fixed: `axio` → `axios`
- Reason: Corrected the package name for the Axios HTTP client library
- Fixed: `iteract` → `interact`
- Reason: Corrected spelling of the word "interact"
- Fixed: `auxiliar` → `auxiliary`
- Reason: Corrected spelling of the word "auxiliary"
This PR fixes several typos in the documentation files:
1. Corrects the Axios package name in the installation command
2. Fixes the spelling of "interact" in the providers package description
3. Corrects the spelling of "auxiliary" in the utils package description
These changes improve the documentation accuracy and readability for users of the POAP packages.
>  Fix typos in documentation files

- docs/pages/packages/utils/Queries.mdx
- packages/utils/src/queries/filter.ts
- packages/utils/src/types/filter.ts
> feat: Add `_is_null` filter in query helpers

- packages/drops/package.json
- packages/frames/package.json
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- rollup.base.config.js
- yarn.lock
It's currently not possible to use interfaces and types in consuming projects with `moduleResolution: bundler` configured, because the `.d.mts` file contains bundled js code instead of the type declarations.
The issue comes from [this commit](https://github.com/poap-xyz/poap.js/commit/b13d10f8f0ba55247abbeb690e127f66aa6e1979). The original intention was to rename `.d.ts` into `.d.mts` and `.d.cts`. However, the result was that `.cjs` and `.mts` files were mistakenly renamed to `.d.cts` and `.d.mts`, respectively.
It had good intentions, because it's true that typescript will prioritize reading a `.mts` file over a `.d.ts` file when using `esm`.
To fix this, this PR removes this step in the build process, and explicitly defines the path for type declarations in the package exports instead, …
> build: Specify type declaration file in exports

- build.sh
- docs/pages/changelog.mdx
- docs/pages/packages/utils/Queries.mdx
- packages/drops/package.json
- packages/drops/src/DropsClient.ts
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- packages/utils/src/queries/filter.ts
- packages/utils/src/validation/isFilterValueDefined.ts
- packages/utils/test/validation/isFilterValueDefined.spec.ts
- yarn.lock
* `createEqFilter` will now accept 0 or false, for example. Will refuse actually undefined values.
* Also remove `createBoolFilter` as it's the same as `createEqFilter`. (I'm open to different opinions on this, we could deprecate or keep it).
* (minor) Added printing of the name of the package being built in the build script.
Found this when trying to use `createGtFilter('...', 0)` and my filter wouldn't be applied.
> feat: Improve how values are validated in filter utils

- packages/drops/package.json
- packages/moments/package.json
- packages/poaps/package.json
- packages/providers/package.json
- packages/utils/package.json
- packages/utils/src/validation/isFilterValueDefined.ts
- packages/utils/test/validation/isFilterValueDefined.spec.ts
- yarn.lock
It's sometimes valid to give an empty array, or the number 0 to a query. We should allow it.
> feat: Relax query util value validations

- packages/poap-sdk/package.json
- rollup.base.config.js
It was removed to use directories in the build, but it's needed for some libraries to find the entrypoint of the lib.
> build: Keep entrypoint file in package export

- docs/pages/changelog.mdx
- packages/poap-sdk/package.json
- packages/poap-sdk/src/drops/DropsClient.ts
- packages/poap-sdk/src/drops/types/FetchDropsInput.ts
Goal of the PR is to clean up the properties a little to prepare for adding more filters, like fetch drops in Collection, drops by artist, moments, etc.
Changes:
* Remove fetch by name. Replaced by search.
* Remove fetch by "is private". Not a relevant property anymore.
* Update the fetch by date range to include start and end dates.
(up for discussion)
> [Drops] refactor: Clean up fetch drops input

- package.json
- src/poaps/PoapsClient.ts
- src/poaps/queries/PaginatedPoaps.ts
- src/poaps/types/FetchPoapsInput.ts
- test/poaps/PoapsClient.spec.ts
* Same filters and options as `PoapsClient.fetch`, but returns the total count.
> feat: Add `PoapsClient.fetchCount` function

- scripts/publish-sdk
noticed the script could silently continue on failures or unset variables, which could cause incorrect results.
* added `set -euo pipefail` so the script exits immediately on errors and avoids using empty vars.
* updated `remote_version` extraction with:
```bash
remote_version=$(pnpm info "$pkg_name" version --json 2>/dev/null | jq -r '.[0] // .')
```
this handles both array and string outputs from `pnpm`, making the version parsing consistent and reliable.
> fix: script error handling and reliable version extraction

- .gitignore
The file is generate when compiling to check types with `pnpm tsc`
> chore: Add typescript buildinfo file to git ignore
