.github/workflows/run-installs.yml
.gitignore
yarn.lock

Pipeline added for yarn install

---

README.md

I help design the structure of poap.js

Add Agustin Lavarello as contributor

---

examples/moments/backend/package.json
examples/moments/backend/src/index.ts
examples/moments/backend/src/methods/create_moment.ts
packages/attributes/package.json
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/moments/package.json
packages/moments/src/MomentsClient.ts
packages/moments/src/types/input.ts
packages/providers/package.json
packages/providers/src/core/PoapMomentsApi/PoapMomentsApi.ts
packages/providers/src/core/PoapMomentsApi/constants.ts
packages/providers/src/core/PoapMomentsApi/errors/InvalidMediaFileError.ts
packages/providers/src/index.ts
packages/providers/src/ports/MomentsApiProvider/MomentsApiProvider.ts
packages/utils/package.json
yarn.lock

Moments fix

---

examples/attributes/backend/src/methods/create_attributes.ts

Fix typos in create_attributes.ts

---

examples/drops/backend/src/methods/fetch_multiple_drops.ts
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/drops/src/domain/Drop.ts
packages/drops/src/queries/PaginatedDrop.ts
packages/moments/package.json
packages/providers/package.json
packages/utils/package.json

Added power and transfers

---

examples/drops/backend/src/index.ts
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/drops/src/domain/Drop.ts
packages/drops/src/queries/PaginatedDrop.ts
packages/moments/package.json
packages/providers/package.json
packages/utils/package.json

Added poap count and transfer claim

---

examples/drops/backend/src/methods/create_drop.ts
examples/drops/backend/src/methods/fetch_multiple_drops.ts
examples/drops/backend/src/methods/fetch_single_drop.ts
examples/moments/backend/src/index.ts
examples/moments/backend/src/methods/create_moment.ts
examples/moments/backend/src/methods/fetch_moments_by_drop_ids.ts
examples/moments/backend/src/methods/fetch_single_moment.ts
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/drops/src/queries/utils.ts
packages/drops/src/types/input.ts
packages/moments/package.json
packages/moments/src/MomentsClient.ts
packages/moments/src/queries/utils.ts
packages/moments/src/types/input.ts
packages/providers/package.json
packages/utils/package.json

fetch by  multiple id

---

examples/drops/backend/src/methods/fetch_multiple_drops.ts
examples/drops/backend/src/methods/fetch_single_drop.ts
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/drops/src/index.ts
packages/moments/package.json
packages/poaps/package.json
packages/poaps/src/index.ts
packages/providers/package.json
packages/utils/package.json

Added filter by string instead of boolean

---

packages/drops/package.json
packages/drops/src/domain/Drop.ts
packages/drops/src/index.ts
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json

Serialazable drop

---

packages/drops/package.json
packages/drops/src/domain/Drop.ts
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json

Fix serializable drop

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/poaps/src/PoapsClient.ts
packages/poaps/src/queries/utils.ts
packages/providers/package.json
packages/utils/package.json

Address filter

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/poaps/src/PoapsClient.ts
packages/providers/package.json
packages/utils/package.json

Fixed minted on date

---

examples/poaps/backend/src/methods/fetch_multiple_poaps_by_drop_id.ts
packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/poaps/src/PoapsClient.ts
packages/poaps/src/queries/utils.ts
packages/poaps/src/types/input.ts
packages/providers/package.json
packages/utils/package.json
yarn.lock

Fixed filter by null address

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/providers/src/core/PoapDropApi/PoapDropApi.ts
packages/utils/package.json
yarn.lock

Upgrade the base url for poap server

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/providers/src/core/AuthenticationProviderHttp/AuthenticationProviderHttp.ts
packages/utils/package.json
yarn.lock

Fix OAuth Server domain

---

packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/types/input.ts

Fixes # [27](https://github.com/poap-xyz/poap.js/issues/27)

Created new interface to extend for inputs

---

packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/queries/utils.ts

Plt 1403 move all queries to utils

---

examples/drops/backend/package.json
examples/drops/backend/src/index.ts
examples/moments/backend/package.json
examples/moments/backend/src/index.ts
examples/poaps/backend/package.json
examples/poaps/backend/src/index.ts
package-order.sh
packages/performance/package.json
packages/performance/rollup.config.js
packages/performance/src/index.ts
packages/performance/tsconfig.json
yarn.lock

Plt 1392 centralize performance analysis code for reusability across examples 25

---

packages/drops/package.json
packages/moments/package.json
packages/moments/src/client/MomentsClient.spec.ts
packages/moments/src/client/MomentsClient.ts
packages/moments/src/domain/Moment.ts
packages/providers/package.json
packages/providers/src/core/PoapMomentsApi/PoapMomentsApi.ts
packages/providers/src/core/PoapMomentsApi/errors/InvalidMediaError.ts
packages/providers/src/core/PoapMomentsApi/errors/InvalidMediaFileError.ts
packages/providers/src/core/index.ts
packages/providers/src/index.ts
packages/providers/src/ports/MomentsApiProvider/Types/CreateMomentInput.ts
packages/providers/src/ports/MomentsApiProvider/Types/CreateMomentResponse.ts
packages/providers/test/PoapMomentsApi.spec.ts
yarn.lock

Added the new Moments create flow

Refactor new Moments upload flow

---

.gitignore
examples/moments/backend/src/methods/create_moment.ts
package.json
packages/drops/package.json
packages/moments/package.json
packages/moments/src/client/MomentsClient.spec.ts
packages/moments/src/client/MomentsClient.ts
packages/moments/src/client/dtos/create/CreateInput.ts
packages/moments/src/client/dtos/create/CreateMedia.ts
packages/performance/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json
yarn.lock

- Refactor the way we send medias in the create moment method

Refactor Moment Create Medias

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json

Version 0.1.2

---

README.md

Added deploy badge

---

.github/workflows/npm_publish.yml
.github/workflows/npm_publish_tag.yml
.github/workflows/run-tests.yml

Update actions version

---

examples/drops/backend/src/index.ts
examples/drops/backend/src/methods/fetch_drop_image.ts
packages/drops/package.json
packages/drops/src/DropsClient.ts
packages/drops/src/queries/DropImage.ts
packages/drops/src/queries/PaginatedDrop.ts
packages/drops/src/queries/index.ts
packages/drops/src/types/dropImage.ts
packages/drops/src/types/index.ts

feat(IEX-910): Add method to fetch a drop image object

---

packages/providers/src/ports/index.ts

Find out that the error need to be exported too to be usable from outside.

Export `CompassRequestError`

---

docs/pages/packages/_meta.json
docs/pages/packages/frames.mdx
packages/frames/src/Frame.ts

Add docs pages for `@poap-xyz/frames`.

docs: Add documentation for the @poap-xyz/frames package

---

docs/pages/packages/drops.mdx
docs/pages/packages/drops/SearchDrops.mdx
docs/pages/packages/drops/_meta.json
packages/drops/README.md
packages/drops/src/DropsClient.ts
packages/drops/src/queries/SearchDrops.ts
packages/drops/src/types/DropImageResponse.ts
packages/drops/src/types/DropResponse.ts
packages/drops/src/types/SearchDropsInput.ts
packages/drops/src/types/index.ts
packages/utils/src/format/index.ts
packages/utils/src/format/removeSpecialCharacters.ts
packages/utils/src/index.ts
packages/utils/src/validation/index.ts
packages/utils/src/validation/isNumeric.ts

Implements search drops copied from the implementation in collections.
Fixes #101

Search drops

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json
yarn.lock

After many changes in providers, it's time for a new release.

Release Version 0.1.8

---

docs/pages/changelog.mdx
docs/pages/packages/utils/Queries.mdx
examples/poaps/backend/src/methods/fetch_multiple_poaps_by_drop_id.ts
packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/poaps/src/PoapsClient.ts
packages/poaps/src/types/input.ts
packages/providers/package.json
packages/utils/package.json
packages/utils/src/queries/filter.ts
packages/utils/src/queries/order.ts
packages/utils/src/types/filter.ts
packages/utils/src/types/index.ts
packages/utils/src/types/input.ts
packages/utils/src/types/order.ts
packages/utils/src/types/pagination.ts
yarn.lock

During migration found that the filter needs to be recursive.

Filter recursive

---

examples/drops/backend/package.json
examples/frames/package.json
examples/poaps/backend/package.json
packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json
yarn.lock

Bump axios to latest version.
Tested with the beta version.

bump axios to latest version

---

README.md

Changed the documentation in the README.md

[ Documentation ] Changed documentation in README.md

---

.github/PULL_REQUEST_TEMPLATE.md

docs: Fix link to contributing guidelines in pull request template

---

.github/PULL_REQUEST_TEMPLATE.md

When using "Closes" instead of "Fixes", a proper link is added to the issue and upon merging the PR, the issue will automatically be closed.

chore: Link issues properly in pull request template

---

packages/drops/package.json
packages/moments/package.json
packages/poaps/package.json
packages/providers/package.json
packages/utils/package.json
yarn.lock

build: Update all packages to 0.7.1

---

docs/pages/index.mdx

Hey !
I fixed several spelling issues.Glad I could help .
Br, Guayaba221.

docs fix spelling issues

---

packages/providers/src/ports/CollectionsApiProvider/types/CollectionBase.ts
packages/providers/test/PoapCompass.spec.ts
packages/utils/src/queries/field.ts

chore: fix some typos in comment

---

docs/pages/packages/providers/Compass.mdx
docs/pages/packages/utils/Queries.mdx

**Files updated:**
- /docs/pages/packages/providers/Compass.mdx line: 19
- /docs/pages/packages/utils/Queries.mdx line: 73
- /docs/pages/packages/utils/Queries.mdx line: 73
- /docs/pages/packages/utils/Queries.mdx line: 77

Fixed typos

---

packages/frames/package.json

To publish a version with #162

build: Upgrade frames package version to 1.1.2

---

docs/pages/packages/drops/SearchDrops.mdx
docs/pages/packages/moments/FetchMoments.mdx
docs/pages/packages/poaps/FetchPOAPs.mdx

SearchDrops.mdx: Fixed missing article.
FetchMoments.mdx: Fixed subject-verb agreement and verb form.
FetchPOAPs.mdx: Fixed verb tense for clarity.

Grammar and Clarity Improvements in Documentation

---

docs/pages/changelog.mdx
packages/drops/package.json
packages/drops/src/types/DropsSortFields.ts
packages/moments/package.json
packages/moments/src/client/MomentsClient.ts
packages/moments/src/client/dtos/fetch/FetchMomentsInput.ts
packages/moments/src/client/dtos/fetch/MomentsSortFields.ts
packages/poaps/package.json
packages/poaps/src/types/PoapsSortFields.ts
packages/providers/package.json
packages/utils/package.json
yarn.lock

- Fix naming inconsistency
Closes # (issue)

Fix: standardize camelcase

---

docs/pages/packages/drops.mdx
docs/pages/packages/moments.mdx
docs/pages/packages/providers.mdx
packages/drops/README.md
packages/drops/package.json
packages/moments/README.md
packages/moments/package.json
packages/moments/src/client/MomentsClient.spec.ts
packages/moments/src/client/MomentsClient.ts
packages/poaps/package.json
packages/providers/README.md
packages/providers/package.json
packages/providers/src/core/PoapMomentsApi/PoapMomentsApi.ts
packages/providers/test/PoapMomentsApi.spec.ts
packages/utils/package.json
rollup.base.config.js
yarn.lock

* Use fetch instead of axios
* Lose the progress tracking on file uploads. I'm fine with this. We still have the progress on an individual file basis.

build: Remove axios dependency on Moments client

---

docs/pages/packages/poap-sdk/drops/CreateDrop.mdx
docs/pages/packages/poap-sdk/drops/FetchDrops.mdx
docs/pages/packages/poap-sdk/drops/SearchDrops.mdx
docs/pages/packages/poap-sdk/moments/FetchMoments.mdx
docs/pages/packages/poap-sdk/moments/UploadMoments.mdx
docs/pages/packages/poap-sdk/poaps/EmailReservation.mdx
docs/pages/packages/poap-sdk/poaps/Errors.mdx
docs/pages/packages/poap-sdk/poaps/FetchPOAPs.mdx
docs/pages/packages/poap-sdk/poaps/Mint.mdx
docs/pages/packages/poap-sdk/providers/Compass.mdx
docs/pages/packages/poap-sdk/utils/Queries.mdx

Fixes the imports in the documentation.

[Docs] Import flat package

---

packages/poap-sdk/package.json
packages/poap-sdk/src/profiles/ProfilesClient.ts
packages/poap-sdk/src/providers/core/PoapProfilesApi/PoapProfilesApi.ts
packages/poap-sdk/src/providers/ports/ProfilesApiProvider/ProfilesApiProvider.ts

Useful to add headers, or next.js options in next.js projects, for example.

feat: Add options to profile fetch requests

---

packages/poap-sdk/package.json
packages/poap-sdk/src/drops/DropsClient.ts

[Drops] feat: Add request options to drops client fetch

---

packages/poap-sdk/package.json
packages/poap-sdk/src/utils/types/order.ts

feat: Add nulls_first and nulls_last options to Order enum

---

packages/poap-sdk/package.json
packages/poap-sdk/src/drops/DropsClient.ts
packages/poap-sdk/src/drops/domain/Drop.ts
packages/poap-sdk/src/drops/queries/PaginatedDrop.ts
packages/poap-sdk/src/drops/queries/SearchDrops.ts
packages/poap-sdk/src/drops/types/FetchDropsInput.ts
packages/poap-sdk/src/drops/types/SearchDropsInput.ts
packages/poap-sdk/src/moments/client/MomentsClient.spec.ts
packages/poap-sdk/src/moments/client/MomentsClient.ts
packages/poap-sdk/src/moments/client/MomentsClientFactory/MomentsClientFactory.ts
packages/poap-sdk/src/moments/client/MomentsClientFactory/options/GetMomentsDefaultClientOptions.ts
packages/poap-sdk/src/moments/client/dtos/fetch/FetchMomentsInput.ts
packages/poap-sdk/src/moments/domain/Moment.ts
packages/poap-sdk/src/moments/queries/PaginatedMoments.ts
packages/poap-sdk/src/poaps/PoapsClient.ts
packages/poap-sdk/src/poaps/queries/PaginatedPoaps.ts
packages/poap-sdk/src/poaps/types/FetchPoapsInput.ts
packages/poap-sdk/src/poaps/utils/MintChecker.ts
packages/poap-sdk/src/poaps/utils/PoapIndexed.ts
packages/poap-sdk/src/poaps/utils/RetryableTask.ts
packages/poap-sdk/test/poaps/PoapsClient.spec.ts

Helps avoid circular references.

Relative imports

---

docs/pages/features.mdx
docs/pages/modules/_meta.json
docs/pages/modules/collections/GetCollection.mdx
docs/pages/modules/collections/ListCollections.mdx
docs/pages/modules/collections/SearchCollections.mdx
docs/pages/modules/collections/_meta.json
docs/pages/modules/drops/FetchDrops.mdx
package.json
src/collections/CollectionsClient.ts
src/collections/domain/Collection.ts
src/collections/domain/CollectionType.ts
src/collections/index.ts
src/collections/queries/Collection.ts
src/collections/queries/CollectionDropIds.ts
src/collections/queries/PaginatedCollections.ts
src/collections/queries/SearchCollections.ts
src/collections/types/CollectionResponse.ts
src/collections/types/ListCollectionsInput.ts
src/collections/types/SearchCollectionsInput.ts
src/drops/DropsClient.ts
src/index.ts
src/utils/types/pagination.ts

* 3 functions: `get`, `list`, and `search`
* TODO in next PRs:
* Add Collections API Provider to `CollectionsClient` (to have `create` and `update`), and consolidate types.
* Have some option to get the named sections with their drops in the correct chosen order.

feat: Add collections module

---

docs/pages/changelog.mdx

* Taken from the github releases
* Also reverse the order to have the most recent version first in the document.
Result:

docs: Add full changelog to docs
